CREATE TABLE users (
    id            UUID PRIMARY KEY,
    email         VARCHAR(254) NOT NULL UNIQUE,
    account_name  VARCHAR(20)  NOT NULL UNIQUE,
    display_name  VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

-- id is generated by the client so a retried send cannot create a duplicate
CREATE TABLE messages (
    id           UUID PRIMARY KEY,
    sender_id    UUID        NOT NULL REFERENCES users (id),
    recipient_id UUID        NOT NULL REFERENCES users (id),
    body         TEXT        NOT NULL,
    sent_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX messages_pair_sent_at_idx ON messages (sender_id, recipient_id, sent_at DESC);
CREATE INDEX messages_recipient_idx ON messages (recipient_id);
